#!/bin/bash
# prepare-kernel.sh — Prepare the Asuswrt-Merlin kernel source tree for module
# compilation. Locates the correct source directory, injects FOU kernel config
# options, and runs the minimum make targets needed for out-of-tree module builds.
#
# Environment:
#   MERLIN_SRC  — Path to the cloned asuswrt-merlin.ng repo (default: ./asuswrt-merlin.ng)

set -euo pipefail

readonly MERLIN_SRC="${MERLIN_SRC:-${GITHUB_WORKSPACE:-.}/asuswrt-merlin.ng}"
readonly CROSS_COMPILE="${CROSS_COMPILE:-aarch64-linux-}"
readonly ARCH="arm64"

# ---------------------------------------------------------------------------
# Helpers — all output goes to stderr so subshell $() captures are clean
# ---------------------------------------------------------------------------

log()  { echo "::notice::$*"  >&2; }
warn() { echo "::warning::$*" >&2; }
err()  { echo "::error::$*"   >&2; }

die()  { err "$@"; exit 1; }

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

# Locate the HND SDK source directory for the RT-AX68U.
# Returns the path on stdout; all messages go to stderr.
find_src_rt_dir() {
    local base="${MERLIN_SRC}/release"
    local candidates=(
        "src-rt-5.02L.07p2axhnd"
        "src-rt-5.02axhnd"
        "src-rt-5.04axhnd.675x"
        "src-rt-5.04axhnd"
    )

    for candidate in "${candidates[@]}"; do
        if [[ -d "${base}/${candidate}" ]]; then
            echo "${base}/${candidate}"
            return 0
        fi
    done

    # Fallback: glob for any src-rt-5.0* directory
    local found
    found=$(find "$base" -maxdepth 1 -type d -name 'src-rt-5.0*' 2>/dev/null | sort | head -1)
    if [[ -n "$found" ]]; then
        warn "Using fallback source directory: $(basename "$found")"
        echo "$found"
        return 0
    fi

    die "Could not find HND SDK source directory under ${base}/"
}

# Locate the kernel source directory within the SDK.
# Returns the path on stdout; all messages go to stderr.
find_kernel_dir() {
    local src_rt="$1"
    local candidates=(
        "${src_rt}/kernel/linux-4.1"
        "${src_rt}/kernel/linux-4.19"
        "${src_rt}/linux/linux-4.1"
    )

    for candidate in "${candidates[@]}"; do
        if [[ -d "$candidate" ]]; then
            echo "$candidate"
            return 0
        fi
    done

    # Fallback: glob
    local found
    found=$(find "$src_rt" -maxdepth 2 -type d -name 'linux-4.*' 2>/dev/null | sort | head -1)
    if [[ -n "$found" ]]; then
        warn "Using fallback kernel directory: $found"
        echo "$found"
        return 0
    fi

    die "Could not find kernel source directory under ${src_rt}/"
}

# Create stub Kconfig.autogen files required by the Broadcom HND kernel.
#
# The HND kernel's Kconfig.bcm includes "../../bcmdrivers/Kconfig.autogen"
# which is normally generated by the top-level firmware build system. Since
# we only need to compile net/ipv4 modules, an empty stub is sufficient.
create_kconfig_stubs() {
    local src_rt="$1"

    log "Creating Kconfig.autogen stubs for Broadcom HND build system..."

    local bcmdrivers_dir="${src_rt}/bcmdrivers"
    if [[ -d "$bcmdrivers_dir" ]]; then
        local autogen="${bcmdrivers_dir}/Kconfig.autogen"
        if [[ ! -f "$autogen" ]]; then
            log "  Creating empty stub: bcmdrivers/Kconfig.autogen"
            touch "$autogen"
        else
            log "  bcmdrivers/Kconfig.autogen already exists"
        fi
    else
        warn "bcmdrivers directory not found at ${bcmdrivers_dir} — stub may not be created"
    fi
}

# Locate the RT-AX68U defconfig.
# Returns the path on stdout; all messages go to stderr.
# Returns empty string if nothing found.
find_defconfig() {
    local kernel_dir="$1"
    local src_rt="$2"

    # Priority order: most specific → least specific
    local candidates=(
        "${kernel_dir}/arch/${ARCH}/configs/bcm94906_defconfig"
        "${kernel_dir}/arch/${ARCH}/configs/bcm_94906_defconfig"
        "${kernel_dir}/arch/${ARCH}/configs/rt-ax68u_defconfig"
        "${src_rt}/targets/94906GW/94906GW"
        "${kernel_dir}/.config"
    )

    for candidate in "${candidates[@]}"; do
        if [[ -f "$candidate" ]]; then
            echo "$candidate"
            return 0
        fi
    done

    # Broader search in targets/ for 94906/4906 configs
    if [[ -d "${src_rt}/targets" ]]; then
        local found
        found=$(find "${src_rt}/targets" -maxdepth 3 -type f \
            \( -name '*4906*' -o -name '*94906*' \) \
            2>/dev/null | head -1)
        if [[ -n "$found" ]]; then
            warn "Using target config: ${found#${src_rt}/}"
            echo "$found"
            return 0
        fi
    fi

    # Search arch configs for any bcm/4906 match
    if [[ -d "${kernel_dir}/arch/${ARCH}/configs" ]]; then
        local found
        found=$(find "${kernel_dir}/arch/${ARCH}/configs" -maxdepth 1 -type f \
            \( -name '*4906*' -o -name '*94906*' -o -name '*bcm9*' \) \
            2>/dev/null | head -1)
        if [[ -n "$found" ]]; then
            warn "Using arch defconfig: $(basename "$found")"
            echo "$found"
            return 0
        fi

        # Last resort: any defconfig in arch/arm64/configs
        found=$(find "${kernel_dir}/arch/${ARCH}/configs" -maxdepth 1 -type f \
            -name '*defconfig' 2>/dev/null | head -1)
        if [[ -n "$found" ]]; then
            warn "Last resort defconfig: $(basename "$found")"
            echo "$found"
            return 0
        fi
    fi

    # Nothing found
    echo ""
}

# Inject FOU-related config options AND required Broadcom chip values.
# BCM4906 chip ID is 0x4906 = 18694 decimal.
# These mandatory Kconfig symbols have no defaults and would cause
# silentoldconfig to abort with "aborted!" in non-interactive mode.
inject_config() {
    local config_file="$1"

    log "Injecting FOU kernel config options into $(basename "$config_file")"

    # BCM4906-specific mandatory symbols (chip ID, revision, scheduler params)
    # silentoldconfig aborts if these are missing/empty with no default.
    # BCM_CHIP_NUMBER: Kconfig 'int'  — decimal 18694 (= 0x4906)
    # BRCM_CHIP_REV:  Kconfig 'hex'  — 0x10 (hex type uses 0x prefix in .config)
    # BCM_SCHED_RT_*: Kconfig 'int'  — decimal microseconds
    local broadcom_configs=(
        "CONFIG_BCM_CHIP_NUMBER=18694"
        "CONFIG_BRCM_CHIP_REV=0x10"
        "CONFIG_BCM_SCHED_RT_PERIOD=1000000"
        "CONFIG_BCM_SCHED_RT_RUNTIME=950000"
    )

    # FOU module configs
    local fou_configs=(
        "CONFIG_NET_FOU=m"
        "CONFIG_NET_UDP_TUNNEL=m"
        "CONFIG_INET_UDP_DIAG=m"
    )

    local all_configs=("${broadcom_configs[@]}" "${fou_configs[@]}")

    for cfg in "${all_configs[@]}"; do
        local key="${cfg%%=*}"
        # Remove any existing setting for this key
        sed -i "/^${key}[= ]/d" "$config_file"
        sed -i "/^# ${key} is not set/d" "$config_file"
        # Append the desired setting
        echo "$cfg" >> "$config_file"
        log "  Set ${cfg}"
    done
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    log "Preparing kernel source tree for FOU module compilation..."

    if [[ ! -d "$MERLIN_SRC" ]]; then
        die "Merlin source directory not found: $MERLIN_SRC"
    fi

    # Find SDK and kernel directories
    local src_rt_dir
    src_rt_dir=$(find_src_rt_dir)
    log "SDK directory: $(basename "$src_rt_dir")"

    local kernel_dir
    kernel_dir=$(find_kernel_dir "$src_rt_dir")
    log "Kernel directory: ${kernel_dir#${MERLIN_SRC}/}"

    # Create Kconfig stubs before any make target that parses Kconfig
    create_kconfig_stubs "$src_rt_dir"

    # Handle .config seeding.
    # arch/arm64/configs/defconfig IS the Broadcom HND defconfig (only one exists).
    # We use it as a base and overlay our mandatory BCM4906 chip values on top.
    if [[ -f "${kernel_dir}/.config" ]]; then
        log "Using existing .config"
    else
        local base_defconfig="${kernel_dir}/arch/${ARCH}/configs/defconfig"
        if [[ -f "$base_defconfig" ]]; then
            log "Using kernel defconfig: arch/${ARCH}/configs/defconfig"
            cp "$base_defconfig" "${kernel_dir}/.config"
        else
            warn "No defconfig found — starting from empty .config"
            touch "${kernel_dir}/.config"
        fi
    fi

    # Inject BCM4906 mandatory values + FOU module config.
    # These values must come AFTER copying the defconfig so they take precedence.
    inject_config "${kernel_dir}/.config"

    # Common make flags for all kernel targets
    local make_flags=(
        -C "$kernel_dir"
        ARCH="$ARCH"
        CROSS_COMPILE="$CROSS_COMPILE"
        KCONFIG_NOTIMESTAMP=1
        V=1
    )

    # Run olddefconfig — accepts all defaults non-interactively.
    # Pipe 'yes ""' as a safety net for any remaining mandatory prompts.
    log "Running: make olddefconfig"
    yes "" | make "${make_flags[@]}" olddefconfig || make "${make_flags[@]}" olddefconfig

    # modules_prepare builds scripts/ and generates include/config/auto.conf.
    # Pipe 'yes ""' to handle any silentoldconfig prompts that remain.
    log "Running: make modules_prepare"
    yes "" | make "${make_flags[@]}" modules_prepare

    # Verify FOU is configured as a module
    if grep -q "CONFIG_NET_FOU=m" "${kernel_dir}/.config"; then
        log "✓ CONFIG_NET_FOU=m confirmed in .config"
    else
        die "CONFIG_NET_FOU=m not found in .config after preparation"
    fi

    # Export the kernel directory for subsequent steps
    if [[ -n "${GITHUB_ENV:-}" ]]; then
        echo "KERNEL_DIR=${kernel_dir}" >> "$GITHUB_ENV"
        echo "SRC_RT_DIR=${src_rt_dir}" >> "$GITHUB_ENV"
    fi

    log "Kernel preparation complete: ${kernel_dir}"
}

main "$@"
