#!/bin/bash
# prepare-kernel.sh — Prepare the Asuswrt-Merlin kernel source tree for module
# compilation. Locates the correct source directory, injects FOU kernel config
# options, and runs the minimum make targets needed for out-of-tree module builds.
#
# Environment:
#   MERLIN_SRC  — Path to the cloned asuswrt-merlin.ng repo (default: ./asuswrt-merlin.ng)

set -euo pipefail

readonly MERLIN_SRC="${MERLIN_SRC:-${GITHUB_WORKSPACE:-.}/asuswrt-merlin.ng}"
readonly CROSS_COMPILE="${CROSS_COMPILE:-aarch64-linux-}"
readonly ARCH="arm64"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log()  { echo "::notice::$*"; }
warn() { echo "::warning::$*"; }
err()  { echo "::error::$*"; >&2 echo "ERROR: $*"; }

die() { err "$@"; exit 1; }

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

# Locate the HND SDK source directory for the RT-AX68U
# Tries several known directory patterns in order of likelihood.
find_src_rt_dir() {
    local base="${MERLIN_SRC}/release"
    local candidates=(
        "src-rt-5.02L.07p2axhnd"
        "src-rt-5.02axhnd"
        "src-rt-5.04axhnd.675x"
        "src-rt-5.04axhnd"
    )

    for candidate in "${candidates[@]}"; do
        if [[ -d "${base}/${candidate}" ]]; then
            echo "${base}/${candidate}"
            return 0
        fi
    done

    # Fallback: glob for any src-rt-5.0* directory
    local found
    found=$(find "$base" -maxdepth 1 -type d -name 'src-rt-5.0*' | sort | head -1)
    if [[ -n "$found" ]]; then
        warn "Using fallback source directory: $(basename "$found")"
        echo "$found"
        return 0
    fi

    die "Could not find HND SDK source directory under ${base}/"
}

# Locate the kernel source directory within the SDK
find_kernel_dir() {
    local src_rt="$1"
    local candidates=(
        "${src_rt}/kernel/linux-4.1"
        "${src_rt}/kernel/linux-4.19"
        "${src_rt}/linux/linux-4.1"
    )

    for candidate in "${candidates[@]}"; do
        if [[ -d "$candidate" ]]; then
            echo "$candidate"
            return 0
        fi
    done

    # Fallback: glob
    local found
    found=$(find "$src_rt" -maxdepth 2 -type d -name 'linux-4.*' | sort | head -1)
    if [[ -n "$found" ]]; then
        warn "Using fallback kernel directory: $found"
        echo "$found"
        return 0
    fi

    die "Could not find kernel source directory under ${src_rt}/"
}

# Create stub Kconfig.autogen files required by the Broadcom HND kernel.
#
# The HND kernel's Kconfig.bcm includes "../../bcmdrivers/Kconfig.autogen"
# which is normally generated by the top-level firmware build system. Since
# we only need to compile net/ipv4 modules, an empty stub is sufficient to
# let kconfig parse without error.
create_kconfig_stubs() {
    local src_rt="$1"
    local kernel_dir="$2"

    log "Creating Kconfig.autogen stubs for Broadcom HND build system..."

    # The kernel Kconfig.bcm references ../../bcmdrivers/Kconfig.autogen
    # relative to the kernel source dir. Resolve that path.
    local bcmdrivers_dir="${src_rt}/bcmdrivers"
    if [[ -d "$bcmdrivers_dir" ]]; then
        local autogen="${bcmdrivers_dir}/Kconfig.autogen"
        if [[ ! -f "$autogen" ]]; then
            log "  Creating empty stub: bcmdrivers/Kconfig.autogen"
            touch "$autogen"
        else
            log "  Kconfig.autogen already exists"
        fi
    else
        warn "bcmdrivers directory not found at ${bcmdrivers_dir}"
        # Try to create it — the Kconfig include is relative to kernel dir
        local rel_path
        rel_path=$(realpath --relative-to="$kernel_dir" "$src_rt")/bcmdrivers
        mkdir -p "${kernel_dir}/${rel_path}" 2>/dev/null || true
        touch "${kernel_dir}/${rel_path}/Kconfig.autogen" 2>/dev/null || true
    fi

    # Also search for any other Kconfig files that source missing autogen files
    # and create stubs for them
    local kconfig_files
    kconfig_files=$(grep -rl 'Kconfig.autogen' "$kernel_dir" 2>/dev/null || true)
    if [[ -n "$kconfig_files" ]]; then
        while IFS= read -r kf; do
            # Extract the relative path referenced in the source/include
            local refs
            refs=$(grep -oE '(source\s+|include\s+)?"[^"]*Kconfig\.autogen"' "$kf" 2>/dev/null \
                | sed 's/.*"\(.*\)"/\1/' || true)
            while IFS= read -r ref; do
                if [[ -n "$ref" ]]; then
                    local target_dir
                    target_dir=$(dirname "$kf")
                    local target_file="${target_dir}/${ref}"
                    if [[ ! -f "$target_file" ]]; then
                        mkdir -p "$(dirname "$target_file")" 2>/dev/null || true
                        touch "$target_file" 2>/dev/null || true
                        log "  Created stub: ${target_file#${src_rt}/}"
                    fi
                fi
            done <<< "$refs"
        done <<< "$kconfig_files"
    fi
}

# Locate the RT-AX68U defconfig or .config
# Searches multiple locations in order of specificity.
find_defconfig() {
    local kernel_dir="$1"
    local src_rt="$2"

    # Try common defconfig locations
    local candidates=(
        "${kernel_dir}/arch/${ARCH}/configs/bcm94906_defconfig"
        "${kernel_dir}/arch/${ARCH}/configs/bcm_94906_defconfig"
        "${kernel_dir}/arch/${ARCH}/configs/rt-ax68u_defconfig"
        "${src_rt}/targets/94906GW/94906GW"
        "${kernel_dir}/.config"
    )

    for candidate in "${candidates[@]}"; do
        if [[ -f "$candidate" ]]; then
            echo "$candidate"
            return 0
        fi
    done

    # Search targets/ directory more broadly for any config referencing 94906
    if [[ -d "${src_rt}/targets" ]]; then
        local found
        found=$(find "${src_rt}/targets" -maxdepth 3 -type f \
            \( -name '*4906*' -o -name '*94906*' -o -name '*.config' -o -name 'defconfig' \) \
            2>/dev/null | head -1)
        if [[ -n "$found" ]]; then
            warn "Using target config: ${found#${src_rt}/}"
            echo "$found"
            return 0
        fi
    fi

    # Search arch configs
    if [[ -d "${kernel_dir}/arch/${ARCH}/configs" ]]; then
        local found
        found=$(find "${kernel_dir}/arch/${ARCH}/configs" -maxdepth 1 -type f \
            \( -name '*4906*' -o -name '*94906*' -o -name '*bcm9*' \) \
            2>/dev/null | head -1)
        if [[ -n "$found" ]]; then
            warn "Using arch defconfig: $(basename "$found")"
            echo "$found"
            return 0
        fi

        # Last resort: use any available defconfig
        found=$(find "${kernel_dir}/arch/${ARCH}/configs" -maxdepth 1 -type f -name '*defconfig' \
            2>/dev/null | head -1)
        if [[ -n "$found" ]]; then
            warn "Using first available defconfig: $(basename "$found")"
            echo "$found"
            return 0
        fi
    fi

    echo ""
}

# Inject FOU-related config options into the kernel .config
inject_config() {
    local config_file="$1"

    log "Injecting FOU kernel config options into $(basename "$config_file")"

    local configs=(
        "CONFIG_NET_FOU=m"
        "CONFIG_NET_UDP_TUNNEL=m"
        "CONFIG_INET_UDP_DIAG=m"
    )

    for cfg in "${configs[@]}"; do
        local key="${cfg%%=*}"
        # Remove any existing setting for this key (enabled, module, or disabled)
        sed -i "/^${key}[= ]/d" "$config_file"
        sed -i "/^# ${key} is not set/d" "$config_file"
        # Append the desired setting
        echo "$cfg" >> "$config_file"
        log "  Set ${cfg}"
    done
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    log "Preparing kernel source tree for FOU module compilation..."

    # Verify Merlin source exists
    if [[ ! -d "$MERLIN_SRC" ]]; then
        die "Merlin source directory not found: $MERLIN_SRC"
    fi

    # Find directories
    local src_rt_dir
    src_rt_dir=$(find_src_rt_dir)
    log "SDK directory: $(basename "$src_rt_dir")"

    local kernel_dir
    kernel_dir=$(find_kernel_dir "$src_rt_dir")
    log "Kernel directory: ${kernel_dir#${MERLIN_SRC}/}"

    # Create Kconfig.autogen stubs before any make target that parses Kconfig
    create_kconfig_stubs "$src_rt_dir" "$kernel_dir"

    # Handle defconfig / .config
    local defconfig
    defconfig=$(find_defconfig "$kernel_dir" "$src_rt_dir")

    if [[ -n "$defconfig" && ! -f "${kernel_dir}/.config" ]]; then
        log "Copying defconfig to .config: $(basename "$defconfig")"
        cp "$defconfig" "${kernel_dir}/.config"
    elif [[ -f "${kernel_dir}/.config" ]]; then
        log "Using existing .config"
    else
        warn "No defconfig found — generating minimal config with make defconfig"
        make -C "$kernel_dir" ARCH="$ARCH" CROSS_COMPILE="$CROSS_COMPILE" defconfig
    fi

    # Inject FOU config
    inject_config "${kernel_dir}/.config"

    # Run kernel preparation targets
    log "Running: make olddefconfig"
    make -C "$kernel_dir" ARCH="$ARCH" CROSS_COMPILE="$CROSS_COMPILE" olddefconfig

    log "Running: make scripts"
    make -C "$kernel_dir" ARCH="$ARCH" CROSS_COMPILE="$CROSS_COMPILE" scripts

    log "Running: make modules_prepare"
    make -C "$kernel_dir" ARCH="$ARCH" CROSS_COMPILE="$CROSS_COMPILE" modules_prepare

    # Verify FOU is configured as a module
    if grep -q "CONFIG_NET_FOU=m" "${kernel_dir}/.config"; then
        log "✓ CONFIG_NET_FOU=m confirmed in .config"
    else
        die "CONFIG_NET_FOU=m not found in .config after preparation"
    fi

    # Export the kernel directory for subsequent scripts
    if [[ -n "${GITHUB_ENV:-}" ]]; then
        echo "KERNEL_DIR=${kernel_dir}" >> "$GITHUB_ENV"
        echo "SRC_RT_DIR=${src_rt_dir}" >> "$GITHUB_ENV"
    fi

    log "Kernel preparation complete: ${kernel_dir}"
}

main "$@"
